// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module Filter2D (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        p_src_data_stream_V_dout,
        p_src_data_stream_V_empty_n,
        p_src_data_stream_V_read,
        p_dst_data_stream_V_din,
        p_dst_data_stream_V_full_n,
        p_dst_data_stream_V_write,
        p_kernel_val_0_V_1_read,
        p_kernel_val_0_V_2_read,
        p_kernel_val_1_V_0_read,
        p_kernel_val_1_V_2_read,
        p_kernel_val_2_V_0_read,
        p_kernel_val_2_V_1_read
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_pp0_stage0 = 4'd4;
parameter    ap_ST_fsm_state7 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] p_src_data_stream_V_dout;
input   p_src_data_stream_V_empty_n;
output   p_src_data_stream_V_read;
output  [7:0] p_dst_data_stream_V_din;
input   p_dst_data_stream_V_full_n;
output   p_dst_data_stream_V_write;
input  [1:0] p_kernel_val_0_V_1_read;
input  [1:0] p_kernel_val_0_V_2_read;
input  [2:0] p_kernel_val_1_V_0_read;
input  [3:0] p_kernel_val_1_V_2_read;
input  [1:0] p_kernel_val_2_V_0_read;
input  [2:0] p_kernel_val_2_V_1_read;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg p_src_data_stream_V_read;
reg p_dst_data_stream_V_write;

(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    p_src_data_stream_V_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0;
reg   [0:0] exitcond388_i_reg_1436;
reg   [0:0] or_cond_i_i_reg_1445;
reg   [0:0] icmp_reg_1401;
reg   [0:0] tmp_s_reg_1392;
reg    p_dst_data_stream_V_blk_n;
reg    ap_enable_reg_pp0_iter3;
reg   [0:0] or_cond_i_reg_1479;
reg   [0:0] or_cond_i_reg_1479_pp0_iter2_reg;
reg   [9:0] t_V_2_reg_333;
wire  signed [9:0] OP2_V_0_1_cast_fu_344_p1;
reg  signed [9:0] OP2_V_0_1_cast_reg_1353;
wire  signed [9:0] OP2_V_0_2_cast_fu_348_p1;
reg  signed [9:0] OP2_V_0_2_cast_reg_1358;
wire  signed [10:0] OP2_V_1_cast_fu_352_p1;
reg  signed [10:0] OP2_V_1_cast_reg_1363;
wire   [11:0] OP2_V_1_2_cast_fu_356_p1;
reg   [11:0] OP2_V_1_2_cast_reg_1368;
wire  signed [9:0] OP2_V_2_cast_fu_360_p1;
reg  signed [9:0] OP2_V_2_cast_reg_1373;
wire   [10:0] OP2_V_2_1_cast_fu_364_p1;
reg   [10:0] OP2_V_2_1_cast_reg_1378;
wire   [0:0] exitcond389_i_fu_372_p2;
wire    ap_CS_fsm_state2;
wire   [8:0] i_V_fu_378_p2;
reg   [8:0] i_V_reg_1387;
wire   [0:0] tmp_s_fu_384_p2;
wire   [0:0] tmp_375_0_not_fu_390_p2;
reg   [0:0] tmp_375_0_not_reg_1396;
wire   [0:0] icmp_fu_406_p2;
wire   [0:0] tmp_2_fu_412_p2;
reg   [0:0] tmp_2_reg_1406;
wire   [0:0] tmp_419_1_fu_418_p2;
reg   [0:0] tmp_419_1_reg_1410;
wire   [0:0] tmp_3_fu_424_p2;
reg   [0:0] tmp_3_reg_1414;
wire   [1:0] row_assign_10_0_t_fu_578_p2;
reg   [1:0] row_assign_10_0_t_reg_1421;
wire   [1:0] row_assign_10_1_t_fu_616_p2;
reg   [1:0] row_assign_10_1_t_reg_1426;
wire   [1:0] row_assign_10_2_t_fu_654_p2;
reg   [1:0] row_assign_10_2_t_reg_1431;
wire   [0:0] exitcond388_i_fu_664_p2;
wire    ap_block_state3_pp0_stage0_iter0;
reg    ap_predicate_op159_read_state4;
reg    ap_predicate_op170_read_state4;
reg    ap_block_state4_pp0_stage0_iter1;
wire    ap_block_state5_pp0_stage0_iter2;
reg    ap_block_state6_pp0_stage0_iter3;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] exitcond388_i_reg_1436_pp0_iter1_reg;
wire   [9:0] j_V_fu_670_p2;
reg    ap_enable_reg_pp0_iter0;
wire   [0:0] or_cond_i_i_fu_722_p2;
wire   [1:0] tmp_69_fu_812_p1;
reg   [1:0] tmp_69_reg_1449;
wire   [0:0] brmerge_fu_816_p2;
reg   [0:0] brmerge_reg_1454;
reg   [9:0] k_buf_0_val_3_addr_reg_1461;
reg   [9:0] k_buf_0_val_4_addr_reg_1467;
reg   [9:0] k_buf_0_val_5_addr_reg_1473;
wire   [0:0] or_cond_i_fu_828_p2;
reg   [0:0] or_cond_i_reg_1479_pp0_iter1_reg;
wire   [7:0] src_kernel_win_0_va_23_fu_960_p3;
reg   [7:0] src_kernel_win_0_va_23_reg_1483;
wire   [7:0] src_kernel_win_0_va_24_fu_978_p3;
reg   [7:0] src_kernel_win_0_va_24_reg_1490;
wire   [7:0] src_kernel_win_0_va_25_fu_996_p3;
reg   [7:0] src_kernel_win_0_va_25_reg_1496;
wire  signed [10:0] grp_fu_1262_p3;
reg  signed [10:0] p_Val2_89_0_1_reg_1501;
reg   [0:0] isneg_reg_1506;
wire   [7:0] p_Val2_2_fu_1185_p2;
reg   [7:0] p_Val2_2_reg_1512;
reg   [3:0] tmp_39_reg_1517;
reg    ap_block_pp0_stage0_subdone;
reg    ap_enable_reg_pp0_iter2;
reg    ap_condition_pp0_exit_iter1_state4;
wire   [9:0] k_buf_0_val_3_address0;
reg    k_buf_0_val_3_ce0;
wire   [7:0] k_buf_0_val_3_q0;
reg    k_buf_0_val_3_ce1;
reg    k_buf_0_val_3_we1;
wire   [9:0] k_buf_0_val_4_address0;
reg    k_buf_0_val_4_ce0;
wire   [7:0] k_buf_0_val_4_q0;
reg    k_buf_0_val_4_ce1;
reg    k_buf_0_val_4_we1;
reg   [7:0] k_buf_0_val_4_d1;
wire   [9:0] k_buf_0_val_5_address0;
reg    k_buf_0_val_5_ce0;
wire   [7:0] k_buf_0_val_5_q0;
reg    k_buf_0_val_5_ce1;
reg    k_buf_0_val_5_we1;
reg   [7:0] k_buf_0_val_5_d1;
reg   [8:0] t_V_reg_322;
wire    ap_CS_fsm_state7;
wire   [63:0] tmp_22_fu_821_p1;
reg    ap_block_pp0_stage0_01001;
reg   [7:0] src_kernel_win_0_va_fu_160;
reg   [7:0] src_kernel_win_0_va_18_fu_164;
reg   [7:0] src_kernel_win_0_va_19_fu_168;
reg   [7:0] src_kernel_win_0_va_20_fu_172;
reg   [7:0] src_kernel_win_0_va_21_fu_176;
reg   [7:0] src_kernel_win_0_va_22_fu_180;
reg   [7:0] right_border_buf_0_s_fu_184;
wire   [7:0] col_buf_0_val_0_0_fu_868_p3;
reg   [7:0] right_border_buf_0_14_fu_188;
reg   [7:0] right_border_buf_0_15_fu_192;
reg   [7:0] right_border_buf_0_16_fu_196;
wire   [7:0] col_buf_0_val_1_0_fu_887_p3;
reg   [7:0] right_border_buf_0_17_fu_200;
reg   [7:0] right_border_buf_0_18_fu_204;
wire   [7:0] col_buf_0_val_2_0_fu_906_p3;
wire   [7:0] tmp_51_fu_396_p4;
wire   [9:0] t_V_cast_fu_368_p1;
wire   [1:0] tmp_52_fu_430_p1;
wire   [9:0] tmp_7_fu_434_p2;
wire   [0:0] tmp_53_fu_446_p3;
wire   [0:0] tmp_10_fu_460_p2;
wire   [0:0] rev_fu_454_p2;
wire   [0:0] tmp_54_fu_472_p3;
wire   [9:0] p_assign_7_fu_480_p2;
wire   [9:0] p_p2_i425_i_fu_486_p3;
wire   [1:0] tmp_55_fu_494_p1;
wire   [9:0] p_assign_6_1_fu_510_p2;
wire   [9:0] p_assign_6_2_fu_536_p2;
wire   [0:0] tmp_13_fu_498_p2;
wire   [1:0] p_assign_8_fu_504_p2;
wire   [0:0] or_cond_i424_i_fu_466_p2;
wire   [1:0] tmp_39_cast_fu_440_p2;
wire   [1:0] p_p2_i425_i_p_assign_8_fu_562_p3;
wire   [1:0] y_1_fu_570_p3;
wire   [1:0] tmp_58_fu_532_p1;
wire   [0:0] tmp_57_fu_524_p3;
wire   [1:0] tmp_62_fu_590_p2;
wire   [1:0] tmp_63_fu_596_p1;
wire   [0:0] tmp_56_fu_516_p3;
wire   [1:0] tmp_36_fu_600_p3;
wire   [1:0] tmp_27_fu_584_p2;
wire   [1:0] tmp_29_fu_608_p3;
wire   [1:0] tmp_61_fu_558_p1;
wire   [0:0] tmp_60_fu_550_p3;
wire   [1:0] tmp_64_fu_628_p2;
wire   [1:0] tmp_65_fu_634_p1;
wire   [0:0] tmp_59_fu_542_p3;
wire   [1:0] tmp_37_fu_638_p3;
wire   [1:0] tmp_31_fu_622_p2;
wire   [1:0] tmp_33_fu_646_p3;
wire   [8:0] tmp_66_fu_676_p4;
wire   [10:0] t_V_2_cast_fu_660_p1;
wire  signed [10:0] ImagLoc_x_fu_692_p2;
wire   [0:0] tmp_67_fu_702_p3;
wire   [0:0] tmp_18_fu_716_p2;
wire   [0:0] rev2_fu_710_p2;
wire   [0:0] tmp_68_fu_728_p3;
wire   [10:0] p_assign_1_fu_736_p2;
wire  signed [10:0] p_p2_i_i_fu_742_p3;
wire  signed [11:0] p_p2_i_i_cast_fu_754_p1;
wire  signed [11:0] ImagLoc_x_cast_fu_698_p1;
wire   [11:0] p_assign_2_fu_764_p2;
wire   [11:0] p_assign_3_fu_770_p3;
wire   [0:0] tmp_18_not_fu_782_p2;
wire   [0:0] tmp_20_fu_758_p2;
wire   [0:0] sel_tmp7_fu_788_p2;
wire   [0:0] sel_tmp8_fu_794_p2;
wire  signed [12:0] p_p2_i_i_cast1_fu_750_p1;
wire   [12:0] sel_tmp_cast_fu_778_p1;
wire  signed [12:0] x_fu_800_p3;
wire  signed [31:0] col_assign_cast_fu_808_p1;
wire   [0:0] icmp2_fu_686_p2;
wire   [1:0] col_assign_3_t_fu_851_p2;
wire   [7:0] tmp_23_fu_856_p5;
wire   [7:0] tmp_24_fu_875_p5;
wire   [7:0] tmp_25_fu_894_p5;
wire   [7:0] tmp_26_fu_949_p5;
wire   [7:0] tmp_30_fu_967_p5;
wire   [7:0] tmp_34_fu_985_p5;
wire   [8:0] OP1_V_0_cast_fu_1009_p1;
wire  signed [8:0] r_V_8_fu_1013_p2;
wire  signed [10:0] grp_fu_1269_p3;
wire  signed [2:0] r_V_8_1_fu_1059_p0;
wire   [7:0] r_V_8_1_fu_1059_p1;
wire  signed [10:0] r_V_8_1_fu_1059_p2;
wire  signed [11:0] tmp_463_1_cast_cast_fu_1064_p1;
wire  signed [11:0] p_Val2_89_0_2_cast_fu_1052_p1;
wire   [3:0] r_V_8_1_2_fu_1084_p0;
wire   [7:0] r_V_8_1_2_fu_1084_p1;
wire   [11:0] r_V_8_1_2_fu_1084_p2;
wire   [7:0] tmp_73_fu_1072_p1;
wire   [7:0] tmp_72_fu_1068_p1;
wire  signed [1:0] r_V_8_2_fu_1103_p0;
wire   [7:0] r_V_8_2_fu_1103_p1;
wire   [9:0] r_V_8_2_fu_1103_p2;
wire   [2:0] r_V_8_2_1_fu_1116_p0;
wire   [7:0] r_V_8_2_1_fu_1116_p1;
wire   [10:0] r_V_8_2_1_fu_1116_p2;
wire   [11:0] p_Val2_89_1_1_fu_1075_p2;
wire   [9:0] tmp_463_2_2_cast_cas_fu_1125_p1;
wire   [9:0] tmp5_fu_1134_p2;
wire  signed [10:0] tmp5_cast_fu_1140_p1;
wire   [10:0] tmp4_fu_1144_p2;
wire   [11:0] tmp3_fu_1128_p2;
wire  signed [11:0] tmp4_cast_fu_1150_p1;
wire   [11:0] p_Val2_4_fu_1154_p2;
wire   [7:0] tmp_38_fu_1093_p2;
wire   [7:0] tmp_74_fu_1089_p1;
wire   [7:0] tmp_76_fu_1121_p1;
wire   [7:0] tmp_75_fu_1108_p1;
wire   [7:0] tmp8_fu_1174_p2;
wire   [7:0] tmp6_fu_1168_p2;
wire   [7:0] tmp7_fu_1179_p2;
wire   [0:0] not_i_i_i_fu_1230_p2;
wire   [0:0] tmp_i_i_fu_1225_p2;
wire   [0:0] overflow_fu_1235_p2;
wire   [0:0] tmp_i_i_94_fu_1249_p2;
wire   [7:0] p_mux_i_i_cast_fu_1241_p3;
wire  signed [1:0] grp_fu_1262_p0;
wire   [7:0] grp_fu_1262_p1;
wire  signed [1:0] grp_fu_1269_p0;
wire   [7:0] grp_fu_1269_p1;
reg   [3:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire   [9:0] grp_fu_1262_p10;
wire   [9:0] grp_fu_1269_p10;
wire   [11:0] r_V_8_1_2_fu_1084_p10;
wire   [10:0] r_V_8_1_fu_1059_p10;
wire   [10:0] r_V_8_2_1_fu_1116_p10;
wire   [9:0] r_V_8_2_fu_1103_p10;
reg    ap_condition_336;
reg    ap_condition_51;
reg    ap_condition_330;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
end

Filter2D_1_k_buf_eOg #(
    .DataWidth( 8 ),
    .AddressRange( 752 ),
    .AddressWidth( 10 ))
k_buf_0_val_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_0_val_3_address0),
    .ce0(k_buf_0_val_3_ce0),
    .q0(k_buf_0_val_3_q0),
    .address1(k_buf_0_val_3_addr_reg_1461),
    .ce1(k_buf_0_val_3_ce1),
    .we1(k_buf_0_val_3_we1),
    .d1(p_src_data_stream_V_dout)
);

Filter2D_1_k_buf_eOg #(
    .DataWidth( 8 ),
    .AddressRange( 752 ),
    .AddressWidth( 10 ))
k_buf_0_val_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_0_val_4_address0),
    .ce0(k_buf_0_val_4_ce0),
    .q0(k_buf_0_val_4_q0),
    .address1(k_buf_0_val_4_addr_reg_1467),
    .ce1(k_buf_0_val_4_ce1),
    .we1(k_buf_0_val_4_we1),
    .d1(k_buf_0_val_4_d1)
);

Filter2D_1_k_buf_eOg #(
    .DataWidth( 8 ),
    .AddressRange( 752 ),
    .AddressWidth( 10 ))
k_buf_0_val_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_0_val_5_address0),
    .ce0(k_buf_0_val_5_ce0),
    .q0(k_buf_0_val_5_q0),
    .address1(k_buf_0_val_5_addr_reg_1473),
    .ce1(k_buf_0_val_5_ce1),
    .we1(k_buf_0_val_5_we1),
    .d1(k_buf_0_val_5_d1)
);

image_processing_hbi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
image_processing_hbi_U52(
    .din0(right_border_buf_0_s_fu_184),
    .din1(right_border_buf_0_14_fu_188),
    .din2(8'd0),
    .din3(col_assign_3_t_fu_851_p2),
    .dout(tmp_23_fu_856_p5)
);

image_processing_hbi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
image_processing_hbi_U53(
    .din0(right_border_buf_0_16_fu_196),
    .din1(right_border_buf_0_17_fu_200),
    .din2(8'd0),
    .din3(col_assign_3_t_fu_851_p2),
    .dout(tmp_24_fu_875_p5)
);

image_processing_hbi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
image_processing_hbi_U54(
    .din0(right_border_buf_0_18_fu_204),
    .din1(right_border_buf_0_15_fu_192),
    .din2(8'd0),
    .din3(col_assign_3_t_fu_851_p2),
    .dout(tmp_25_fu_894_p5)
);

image_processing_hbi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
image_processing_hbi_U55(
    .din0(col_buf_0_val_0_0_fu_868_p3),
    .din1(col_buf_0_val_1_0_fu_887_p3),
    .din2(col_buf_0_val_2_0_fu_906_p3),
    .din3(row_assign_10_0_t_reg_1421),
    .dout(tmp_26_fu_949_p5)
);

image_processing_hbi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
image_processing_hbi_U56(
    .din0(col_buf_0_val_0_0_fu_868_p3),
    .din1(col_buf_0_val_1_0_fu_887_p3),
    .din2(col_buf_0_val_2_0_fu_906_p3),
    .din3(row_assign_10_1_t_reg_1426),
    .dout(tmp_30_fu_967_p5)
);

image_processing_hbi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
image_processing_hbi_U57(
    .din0(col_buf_0_val_0_0_fu_868_p3),
    .din1(col_buf_0_val_1_0_fu_887_p3),
    .din2(col_buf_0_val_2_0_fu_906_p3),
    .din3(row_assign_10_2_t_reg_1431),
    .dout(tmp_34_fu_985_p5)
);

image_processing_pcA #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 9 ),
    .dout_WIDTH( 11 ))
image_processing_pcA_U58(
    .din0(grp_fu_1262_p0),
    .din1(grp_fu_1262_p1),
    .din2(r_V_8_fu_1013_p2),
    .dout(grp_fu_1262_p3)
);

image_processing_qcK #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 11 ),
    .dout_WIDTH( 11 ))
image_processing_qcK_U59(
    .din0(grp_fu_1269_p0),
    .din1(grp_fu_1269_p1),
    .din2(p_Val2_89_0_1_reg_1501),
    .dout(grp_fu_1269_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((exitcond388_i_fu_664_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((exitcond389_i_fu_372_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter1_state4)) begin
                ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter0;
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end else if (((exitcond389_i_fu_372_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp0_iter3 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond388_i_fu_664_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        t_V_2_reg_333 <= j_V_fu_670_p2;
    end else if (((exitcond389_i_fu_372_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        t_V_2_reg_333 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        t_V_reg_322 <= i_V_reg_1387;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        t_V_reg_322 <= 9'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        OP2_V_0_1_cast_reg_1353 <= OP2_V_0_1_cast_fu_344_p1;
        OP2_V_0_2_cast_reg_1358 <= OP2_V_0_2_cast_fu_348_p1;
        OP2_V_1_2_cast_reg_1368[3 : 0] <= OP2_V_1_2_cast_fu_356_p1[3 : 0];
        OP2_V_1_cast_reg_1363 <= OP2_V_1_cast_fu_352_p1;
        OP2_V_2_1_cast_reg_1378[2 : 0] <= OP2_V_2_1_cast_fu_364_p1[2 : 0];
        OP2_V_2_cast_reg_1373 <= OP2_V_2_cast_fu_360_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond388_i_fu_664_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        brmerge_reg_1454 <= brmerge_fu_816_p2;
        k_buf_0_val_3_addr_reg_1461 <= tmp_22_fu_821_p1;
        k_buf_0_val_4_addr_reg_1467 <= tmp_22_fu_821_p1;
        k_buf_0_val_5_addr_reg_1473 <= tmp_22_fu_821_p1;
        or_cond_i_i_reg_1445 <= or_cond_i_i_fu_722_p2;
        or_cond_i_reg_1479 <= or_cond_i_fu_828_p2;
        tmp_69_reg_1449 <= tmp_69_fu_812_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        exitcond388_i_reg_1436 <= exitcond388_i_fu_664_p2;
        exitcond388_i_reg_1436_pp0_iter1_reg <= exitcond388_i_reg_1436;
        or_cond_i_reg_1479_pp0_iter1_reg <= or_cond_i_reg_1479;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        i_V_reg_1387 <= i_V_fu_378_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond389_i_fu_372_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        icmp_reg_1401 <= icmp_fu_406_p2;
        row_assign_10_0_t_reg_1421 <= row_assign_10_0_t_fu_578_p2;
        row_assign_10_1_t_reg_1426 <= row_assign_10_1_t_fu_616_p2;
        row_assign_10_2_t_reg_1431 <= row_assign_10_2_t_fu_654_p2;
        tmp_2_reg_1406 <= tmp_2_fu_412_p2;
        tmp_375_0_not_reg_1396 <= tmp_375_0_not_fu_390_p2;
        tmp_3_reg_1414 <= tmp_3_fu_424_p2;
        tmp_419_1_reg_1410 <= tmp_419_1_fu_418_p2;
        tmp_s_reg_1392 <= tmp_s_fu_384_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((or_cond_i_reg_1479_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        isneg_reg_1506 <= p_Val2_4_fu_1154_p2[32'd11];
        p_Val2_2_reg_1512 <= p_Val2_2_fu_1185_p2;
        tmp_39_reg_1517 <= {{p_Val2_4_fu_1154_p2[11:8]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        or_cond_i_reg_1479_pp0_iter2_reg <= or_cond_i_reg_1479_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((or_cond_i_reg_1479 == 1'd1) & (exitcond388_i_reg_1436 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_Val2_89_0_1_reg_1501 <= grp_fu_1262_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op170_read_state4 == 1'b1))) begin
        right_border_buf_0_14_fu_188 <= right_border_buf_0_s_fu_184;
        right_border_buf_0_15_fu_192 <= right_border_buf_0_18_fu_204;
        right_border_buf_0_16_fu_196 <= col_buf_0_val_1_0_fu_887_p3;
        right_border_buf_0_17_fu_200 <= right_border_buf_0_16_fu_196;
        right_border_buf_0_18_fu_204 <= col_buf_0_val_2_0_fu_906_p3;
        right_border_buf_0_s_fu_184 <= col_buf_0_val_0_0_fu_868_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond388_i_reg_1436_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        src_kernel_win_0_va_18_fu_164 <= src_kernel_win_0_va_fu_160;
        src_kernel_win_0_va_19_fu_168 <= src_kernel_win_0_va_24_reg_1490;
        src_kernel_win_0_va_20_fu_172 <= src_kernel_win_0_va_19_fu_168;
        src_kernel_win_0_va_fu_160 <= src_kernel_win_0_va_23_reg_1483;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond388_i_reg_1436 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        src_kernel_win_0_va_21_fu_176 <= src_kernel_win_0_va_25_fu_996_p3;
        src_kernel_win_0_va_22_fu_180 <= src_kernel_win_0_va_21_fu_176;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond388_i_reg_1436 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        src_kernel_win_0_va_23_reg_1483 <= src_kernel_win_0_va_23_fu_960_p3;
        src_kernel_win_0_va_24_reg_1490 <= src_kernel_win_0_va_24_fu_978_p3;
        src_kernel_win_0_va_25_reg_1496 <= src_kernel_win_0_va_25_fu_996_p3;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_condition_pp0_exit_iter1_state4 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter1_state4 = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | ((exitcond389_i_fu_372_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond389_i_fu_372_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_0_val_3_ce0 = 1'b1;
    end else begin
        k_buf_0_val_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_2_reg_1406 == 1'd1) & (or_cond_i_i_reg_1445 == 1'd1) & (icmp_reg_1401 == 1'd0) & (exitcond388_i_reg_1436 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op170_read_state4 == 1'b1)))) begin
        k_buf_0_val_3_ce1 = 1'b1;
    end else begin
        k_buf_0_val_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_2_reg_1406 == 1'd1) & (or_cond_i_i_reg_1445 == 1'd1) & (icmp_reg_1401 == 1'd0) & (exitcond388_i_reg_1436 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op170_read_state4 == 1'b1)))) begin
        k_buf_0_val_3_we1 = 1'b1;
    end else begin
        k_buf_0_val_3_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_0_val_4_ce0 = 1'b1;
    end else begin
        k_buf_0_val_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_419_1_reg_1410 == 1'd1) & (or_cond_i_i_reg_1445 == 1'd1) & (icmp_reg_1401 == 1'd0) & (exitcond388_i_reg_1436 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op170_read_state4 == 1'b1)))) begin
        k_buf_0_val_4_ce1 = 1'b1;
    end else begin
        k_buf_0_val_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_51)) begin
        if ((ap_predicate_op170_read_state4 == 1'b1)) begin
            k_buf_0_val_4_d1 = k_buf_0_val_3_q0;
        end else if ((1'b1 == ap_condition_336)) begin
            k_buf_0_val_4_d1 = p_src_data_stream_V_dout;
        end else begin
            k_buf_0_val_4_d1 = 'bx;
        end
    end else begin
        k_buf_0_val_4_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_419_1_reg_1410 == 1'd1) & (or_cond_i_i_reg_1445 == 1'd1) & (icmp_reg_1401 == 1'd0) & (exitcond388_i_reg_1436 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op170_read_state4 == 1'b1)))) begin
        k_buf_0_val_4_we1 = 1'b1;
    end else begin
        k_buf_0_val_4_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_0_val_5_ce0 = 1'b1;
    end else begin
        k_buf_0_val_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_2_reg_1406 == 1'd1) & (or_cond_i_i_reg_1445 == 1'd1) & (icmp_reg_1401 == 1'd0) & (exitcond388_i_reg_1436 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op170_read_state4 == 1'b1)))) begin
        k_buf_0_val_5_ce1 = 1'b1;
    end else begin
        k_buf_0_val_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_51)) begin
        if ((ap_predicate_op170_read_state4 == 1'b1)) begin
            k_buf_0_val_5_d1 = k_buf_0_val_4_q0;
        end else if ((1'b1 == ap_condition_330)) begin
            k_buf_0_val_5_d1 = p_src_data_stream_V_dout;
        end else begin
            k_buf_0_val_5_d1 = 'bx;
        end
    end else begin
        k_buf_0_val_5_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_2_reg_1406 == 1'd1) & (or_cond_i_i_reg_1445 == 1'd1) & (icmp_reg_1401 == 1'd0) & (exitcond388_i_reg_1436 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op170_read_state4 == 1'b1)))) begin
        k_buf_0_val_5_we1 = 1'b1;
    end else begin
        k_buf_0_val_5_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((or_cond_i_reg_1479_pp0_iter2_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        p_dst_data_stream_V_blk_n = p_dst_data_stream_V_full_n;
    end else begin
        p_dst_data_stream_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((or_cond_i_reg_1479_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_dst_data_stream_V_write = 1'b1;
    end else begin
        p_dst_data_stream_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_s_reg_1392 == 1'd1) & (icmp_reg_1401 == 1'd1) & (or_cond_i_i_reg_1445 == 1'd1) & (exitcond388_i_reg_1436 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((or_cond_i_i_reg_1445 == 1'd1) & (icmp_reg_1401 == 1'd0) & (exitcond388_i_reg_1436 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_src_data_stream_V_blk_n = p_src_data_stream_V_empty_n;
    end else begin
        p_src_data_stream_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op170_read_state4 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op159_read_state4 == 1'b1)))) begin
        p_src_data_stream_V_read = 1'b1;
    end else begin
        p_src_data_stream_V_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((exitcond389_i_fu_372_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b0)) & ~((ap_enable_reg_pp0_iter3 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((ap_enable_reg_pp0_iter3 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b0)))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ImagLoc_x_cast_fu_698_p1 = ImagLoc_x_fu_692_p2;

assign ImagLoc_x_fu_692_p2 = ($signed(11'd2047) + $signed(t_V_2_cast_fu_660_p1));

assign OP1_V_0_cast_fu_1009_p1 = src_kernel_win_0_va_22_fu_180;

assign OP2_V_0_1_cast_fu_344_p1 = $signed(p_kernel_val_0_V_1_read);

assign OP2_V_0_2_cast_fu_348_p1 = $signed(p_kernel_val_0_V_2_read);

assign OP2_V_1_2_cast_fu_356_p1 = p_kernel_val_1_V_2_read;

assign OP2_V_1_cast_fu_352_p1 = $signed(p_kernel_val_1_V_0_read);

assign OP2_V_2_1_cast_fu_364_p1 = p_kernel_val_2_V_1_read;

assign OP2_V_2_cast_fu_360_p1 = $signed(p_kernel_val_2_V_0_read);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd3];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((or_cond_i_reg_1479_pp0_iter2_reg == 1'd1) & (p_dst_data_stream_V_full_n == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((p_src_data_stream_V_empty_n == 1'b0) & (ap_predicate_op170_read_state4 == 1'b1)) | ((p_src_data_stream_V_empty_n == 1'b0) & (ap_predicate_op159_read_state4 == 1'b1)))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((or_cond_i_reg_1479_pp0_iter2_reg == 1'd1) & (p_dst_data_stream_V_full_n == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((p_src_data_stream_V_empty_n == 1'b0) & (ap_predicate_op170_read_state4 == 1'b1)) | ((p_src_data_stream_V_empty_n == 1'b0) & (ap_predicate_op159_read_state4 == 1'b1)))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((or_cond_i_reg_1479_pp0_iter2_reg == 1'd1) & (p_dst_data_stream_V_full_n == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((p_src_data_stream_V_empty_n == 1'b0) & (ap_predicate_op170_read_state4 == 1'b1)) | ((p_src_data_stream_V_empty_n == 1'b0) & (ap_predicate_op159_read_state4 == 1'b1)))));
end

assign ap_block_state3_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state4_pp0_stage0_iter1 = (((p_src_data_stream_V_empty_n == 1'b0) & (ap_predicate_op170_read_state4 == 1'b1)) | ((p_src_data_stream_V_empty_n == 1'b0) & (ap_predicate_op159_read_state4 == 1'b1)));
end

assign ap_block_state5_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state6_pp0_stage0_iter3 = ((or_cond_i_reg_1479_pp0_iter2_reg == 1'd1) & (p_dst_data_stream_V_full_n == 1'b0));
end

always @ (*) begin
    ap_condition_330 = ((tmp_2_reg_1406 == 1'd1) & (or_cond_i_i_reg_1445 == 1'd1) & (icmp_reg_1401 == 1'd0) & (exitcond388_i_reg_1436 == 1'd0));
end

always @ (*) begin
    ap_condition_336 = ((tmp_419_1_reg_1410 == 1'd1) & (or_cond_i_i_reg_1445 == 1'd1) & (icmp_reg_1401 == 1'd0) & (exitcond388_i_reg_1436 == 1'd0));
end

always @ (*) begin
    ap_condition_51 = ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

always @ (*) begin
    ap_predicate_op159_read_state4 = ((or_cond_i_i_reg_1445 == 1'd1) & (icmp_reg_1401 == 1'd0) & (exitcond388_i_reg_1436 == 1'd0));
end

always @ (*) begin
    ap_predicate_op170_read_state4 = ((tmp_s_reg_1392 == 1'd1) & (icmp_reg_1401 == 1'd1) & (or_cond_i_i_reg_1445 == 1'd1) & (exitcond388_i_reg_1436 == 1'd0));
end

assign brmerge_fu_816_p2 = (tmp_375_0_not_reg_1396 | tmp_18_fu_716_p2);

assign col_assign_3_t_fu_851_p2 = (tmp_69_reg_1449 ^ 2'd3);

assign col_assign_cast_fu_808_p1 = x_fu_800_p3;

assign col_buf_0_val_0_0_fu_868_p3 = ((brmerge_reg_1454[0:0] === 1'b1) ? k_buf_0_val_3_q0 : tmp_23_fu_856_p5);

assign col_buf_0_val_1_0_fu_887_p3 = ((brmerge_reg_1454[0:0] === 1'b1) ? k_buf_0_val_4_q0 : tmp_24_fu_875_p5);

assign col_buf_0_val_2_0_fu_906_p3 = ((brmerge_reg_1454[0:0] === 1'b1) ? k_buf_0_val_5_q0 : tmp_25_fu_894_p5);

assign exitcond388_i_fu_664_p2 = ((t_V_2_reg_333 == 10'd754) ? 1'b1 : 1'b0);

assign exitcond389_i_fu_372_p2 = ((t_V_reg_322 == 9'd482) ? 1'b1 : 1'b0);

assign grp_fu_1262_p0 = OP2_V_0_1_cast_reg_1353;

assign grp_fu_1262_p1 = grp_fu_1262_p10;

assign grp_fu_1262_p10 = src_kernel_win_0_va_21_fu_176;

assign grp_fu_1269_p0 = OP2_V_0_2_cast_reg_1358;

assign grp_fu_1269_p1 = grp_fu_1269_p10;

assign grp_fu_1269_p10 = src_kernel_win_0_va_25_reg_1496;

assign i_V_fu_378_p2 = (t_V_reg_322 + 9'd1);

assign icmp2_fu_686_p2 = ((tmp_66_fu_676_p4 != 9'd0) ? 1'b1 : 1'b0);

assign icmp_fu_406_p2 = ((tmp_51_fu_396_p4 != 8'd0) ? 1'b1 : 1'b0);

assign j_V_fu_670_p2 = (t_V_2_reg_333 + 10'd1);

assign k_buf_0_val_3_address0 = tmp_22_fu_821_p1;

assign k_buf_0_val_4_address0 = tmp_22_fu_821_p1;

assign k_buf_0_val_5_address0 = tmp_22_fu_821_p1;

assign not_i_i_i_fu_1230_p2 = ((tmp_39_reg_1517 != 4'd0) ? 1'b1 : 1'b0);

assign or_cond_i424_i_fu_466_p2 = (tmp_10_fu_460_p2 & rev_fu_454_p2);

assign or_cond_i_fu_828_p2 = (icmp_reg_1401 & icmp2_fu_686_p2);

assign or_cond_i_i_fu_722_p2 = (tmp_18_fu_716_p2 & rev2_fu_710_p2);

assign overflow_fu_1235_p2 = (tmp_i_i_fu_1225_p2 & not_i_i_i_fu_1230_p2);

assign p_Val2_2_fu_1185_p2 = (tmp6_fu_1168_p2 + tmp7_fu_1179_p2);

assign p_Val2_4_fu_1154_p2 = ($signed(tmp3_fu_1128_p2) + $signed(tmp4_cast_fu_1150_p1));

assign p_Val2_89_0_2_cast_fu_1052_p1 = grp_fu_1269_p3;

assign p_Val2_89_1_1_fu_1075_p2 = ($signed(tmp_463_1_cast_cast_fu_1064_p1) + $signed(p_Val2_89_0_2_cast_fu_1052_p1));

assign p_assign_1_fu_736_p2 = (11'd1 - t_V_2_cast_fu_660_p1);

assign p_assign_2_fu_764_p2 = ($signed(12'd1502) - $signed(p_p2_i_i_cast_fu_754_p1));

assign p_assign_3_fu_770_p3 = ((or_cond_i_i_fu_722_p2[0:0] === 1'b1) ? ImagLoc_x_cast_fu_698_p1 : p_assign_2_fu_764_p2);

assign p_assign_6_1_fu_510_p2 = ($signed(10'd1022) + $signed(t_V_cast_fu_368_p1));

assign p_assign_6_2_fu_536_p2 = ($signed(10'd1021) + $signed(t_V_cast_fu_368_p1));

assign p_assign_7_fu_480_p2 = (10'd1 - t_V_cast_fu_368_p1);

assign p_assign_8_fu_504_p2 = ($signed(2'd2) - $signed(tmp_55_fu_494_p1));

assign p_dst_data_stream_V_din = ((tmp_i_i_94_fu_1249_p2[0:0] === 1'b1) ? p_mux_i_i_cast_fu_1241_p3 : p_Val2_2_reg_1512);

assign p_mux_i_i_cast_fu_1241_p3 = ((tmp_i_i_fu_1225_p2[0:0] === 1'b1) ? 8'd255 : 8'd0);

assign p_p2_i425_i_fu_486_p3 = ((tmp_54_fu_472_p3[0:0] === 1'b1) ? p_assign_7_fu_480_p2 : tmp_7_fu_434_p2);

assign p_p2_i425_i_p_assign_8_fu_562_p3 = ((tmp_13_fu_498_p2[0:0] === 1'b1) ? tmp_55_fu_494_p1 : p_assign_8_fu_504_p2);

assign p_p2_i_i_cast1_fu_750_p1 = p_p2_i_i_fu_742_p3;

assign p_p2_i_i_cast_fu_754_p1 = p_p2_i_i_fu_742_p3;

assign p_p2_i_i_fu_742_p3 = ((tmp_68_fu_728_p3[0:0] === 1'b1) ? p_assign_1_fu_736_p2 : ImagLoc_x_fu_692_p2);

assign r_V_8_1_2_fu_1084_p0 = OP2_V_1_2_cast_reg_1368;

assign r_V_8_1_2_fu_1084_p1 = r_V_8_1_2_fu_1084_p10;

assign r_V_8_1_2_fu_1084_p10 = src_kernel_win_0_va_24_reg_1490;

assign r_V_8_1_2_fu_1084_p2 = (r_V_8_1_2_fu_1084_p0 * r_V_8_1_2_fu_1084_p1);

assign r_V_8_1_fu_1059_p0 = OP2_V_1_cast_reg_1363;

assign r_V_8_1_fu_1059_p1 = r_V_8_1_fu_1059_p10;

assign r_V_8_1_fu_1059_p10 = src_kernel_win_0_va_20_fu_172;

assign r_V_8_1_fu_1059_p2 = ($signed(r_V_8_1_fu_1059_p0) * $signed({{1'b0}, {r_V_8_1_fu_1059_p1}}));

assign r_V_8_2_1_fu_1116_p0 = OP2_V_2_1_cast_reg_1378;

assign r_V_8_2_1_fu_1116_p1 = r_V_8_2_1_fu_1116_p10;

assign r_V_8_2_1_fu_1116_p10 = src_kernel_win_0_va_fu_160;

assign r_V_8_2_1_fu_1116_p2 = (r_V_8_2_1_fu_1116_p0 * r_V_8_2_1_fu_1116_p1);

assign r_V_8_2_fu_1103_p0 = OP2_V_2_cast_reg_1373;

assign r_V_8_2_fu_1103_p1 = r_V_8_2_fu_1103_p10;

assign r_V_8_2_fu_1103_p10 = src_kernel_win_0_va_18_fu_164;

assign r_V_8_2_fu_1103_p2 = ($signed(r_V_8_2_fu_1103_p0) * $signed({{1'b0}, {r_V_8_2_fu_1103_p1}}));

assign r_V_8_fu_1013_p2 = (9'd0 - OP1_V_0_cast_fu_1009_p1);

assign rev2_fu_710_p2 = (tmp_67_fu_702_p3 ^ 1'd1);

assign rev_fu_454_p2 = (tmp_53_fu_446_p3 ^ 1'd1);

assign row_assign_10_0_t_fu_578_p2 = (y_1_fu_570_p3 ^ 2'd3);

assign row_assign_10_1_t_fu_616_p2 = (tmp_29_fu_608_p3 ^ 2'd3);

assign row_assign_10_2_t_fu_654_p2 = (tmp_33_fu_646_p3 ^ 2'd3);

assign sel_tmp7_fu_788_p2 = (tmp_67_fu_702_p3 | tmp_18_not_fu_782_p2);

assign sel_tmp8_fu_794_p2 = (tmp_20_fu_758_p2 & sel_tmp7_fu_788_p2);

assign sel_tmp_cast_fu_778_p1 = p_assign_3_fu_770_p3;

assign src_kernel_win_0_va_23_fu_960_p3 = ((tmp_3_reg_1414[0:0] === 1'b1) ? tmp_26_fu_949_p5 : col_buf_0_val_0_0_fu_868_p3);

assign src_kernel_win_0_va_24_fu_978_p3 = ((tmp_3_reg_1414[0:0] === 1'b1) ? tmp_30_fu_967_p5 : col_buf_0_val_1_0_fu_887_p3);

assign src_kernel_win_0_va_25_fu_996_p3 = ((tmp_3_reg_1414[0:0] === 1'b1) ? tmp_34_fu_985_p5 : col_buf_0_val_2_0_fu_906_p3);

assign t_V_2_cast_fu_660_p1 = t_V_2_reg_333;

assign t_V_cast_fu_368_p1 = t_V_reg_322;

assign tmp3_fu_1128_p2 = (r_V_8_1_2_fu_1084_p2 + p_Val2_89_1_1_fu_1075_p2);

assign tmp4_cast_fu_1150_p1 = $signed(tmp4_fu_1144_p2);

assign tmp4_fu_1144_p2 = ($signed(r_V_8_2_1_fu_1116_p2) + $signed(tmp5_cast_fu_1140_p1));

assign tmp5_cast_fu_1140_p1 = $signed(tmp5_fu_1134_p2);

assign tmp5_fu_1134_p2 = (tmp_463_2_2_cast_cas_fu_1125_p1 + r_V_8_2_fu_1103_p2);

assign tmp6_fu_1168_p2 = (tmp_38_fu_1093_p2 + tmp_74_fu_1089_p1);

assign tmp7_fu_1179_p2 = (tmp_75_fu_1108_p1 + tmp8_fu_1174_p2);

assign tmp8_fu_1174_p2 = (src_kernel_win_0_va_23_reg_1483 + tmp_76_fu_1121_p1);

assign tmp_10_fu_460_p2 = (($signed(tmp_7_fu_434_p2) < $signed(10'd480)) ? 1'b1 : 1'b0);

assign tmp_13_fu_498_p2 = (($signed(p_p2_i425_i_fu_486_p3) < $signed(10'd480)) ? 1'b1 : 1'b0);

assign tmp_18_fu_716_p2 = (($signed(ImagLoc_x_fu_692_p2) < $signed(11'd752)) ? 1'b1 : 1'b0);

assign tmp_18_not_fu_782_p2 = (tmp_18_fu_716_p2 ^ 1'd1);

assign tmp_20_fu_758_p2 = (($signed(p_p2_i_i_fu_742_p3) < $signed(11'd752)) ? 1'b1 : 1'b0);

assign tmp_22_fu_821_p1 = $unsigned(col_assign_cast_fu_808_p1);

assign tmp_27_fu_584_p2 = (tmp_52_fu_430_p1 ^ 2'd2);

assign tmp_29_fu_608_p3 = ((tmp_56_fu_516_p3[0:0] === 1'b1) ? tmp_36_fu_600_p3 : tmp_27_fu_584_p2);

assign tmp_2_fu_412_p2 = ((t_V_reg_322 == 9'd1) ? 1'b1 : 1'b0);

assign tmp_31_fu_622_p2 = (2'd1 + tmp_52_fu_430_p1);

assign tmp_33_fu_646_p3 = ((tmp_59_fu_542_p3[0:0] === 1'b1) ? tmp_37_fu_638_p3 : tmp_31_fu_622_p2);

assign tmp_36_fu_600_p3 = ((tmp_57_fu_524_p3[0:0] === 1'b1) ? tmp_62_fu_590_p2 : tmp_63_fu_596_p1);

assign tmp_375_0_not_fu_390_p2 = (tmp_s_fu_384_p2 ^ 1'd1);

assign tmp_37_fu_638_p3 = ((tmp_60_fu_550_p3[0:0] === 1'b1) ? tmp_64_fu_628_p2 : tmp_65_fu_634_p1);

assign tmp_38_fu_1093_p2 = (tmp_73_fu_1072_p1 + tmp_72_fu_1068_p1);

assign tmp_39_cast_fu_440_p2 = ($signed(2'd3) + $signed(tmp_52_fu_430_p1));

assign tmp_3_fu_424_p2 = ((t_V_reg_322 > 9'd480) ? 1'b1 : 1'b0);

assign tmp_419_1_fu_418_p2 = ((t_V_reg_322 == 9'd0) ? 1'b1 : 1'b0);

assign tmp_463_1_cast_cast_fu_1064_p1 = r_V_8_1_fu_1059_p2;

assign tmp_463_2_2_cast_cas_fu_1125_p1 = src_kernel_win_0_va_23_reg_1483;

assign tmp_51_fu_396_p4 = {{t_V_reg_322[8:1]}};

assign tmp_52_fu_430_p1 = t_V_reg_322[1:0];

assign tmp_53_fu_446_p3 = tmp_7_fu_434_p2[32'd9];

assign tmp_54_fu_472_p3 = tmp_7_fu_434_p2[32'd9];

assign tmp_55_fu_494_p1 = p_p2_i425_i_fu_486_p3[1:0];

assign tmp_56_fu_516_p3 = p_assign_6_1_fu_510_p2[32'd9];

assign tmp_57_fu_524_p3 = p_assign_6_1_fu_510_p2[32'd9];

assign tmp_58_fu_532_p1 = t_V_reg_322[1:0];

assign tmp_59_fu_542_p3 = p_assign_6_2_fu_536_p2[32'd9];

assign tmp_60_fu_550_p3 = p_assign_6_2_fu_536_p2[32'd9];

assign tmp_61_fu_558_p1 = t_V_reg_322[1:0];

assign tmp_62_fu_590_p2 = ($signed(2'd2) - $signed(tmp_58_fu_532_p1));

assign tmp_63_fu_596_p1 = p_assign_6_1_fu_510_p2[1:0];

assign tmp_64_fu_628_p2 = (tmp_61_fu_558_p1 ^ 2'd3);

assign tmp_65_fu_634_p1 = p_assign_6_2_fu_536_p2[1:0];

assign tmp_66_fu_676_p4 = {{t_V_2_reg_333[9:1]}};

assign tmp_67_fu_702_p3 = ImagLoc_x_fu_692_p2[32'd10];

assign tmp_68_fu_728_p3 = ImagLoc_x_fu_692_p2[32'd10];

assign tmp_69_fu_812_p1 = x_fu_800_p3[1:0];

assign tmp_72_fu_1068_p1 = r_V_8_1_fu_1059_p2[7:0];

assign tmp_73_fu_1072_p1 = grp_fu_1269_p3[7:0];

assign tmp_74_fu_1089_p1 = r_V_8_1_2_fu_1084_p2[7:0];

assign tmp_75_fu_1108_p1 = r_V_8_2_fu_1103_p2[7:0];

assign tmp_76_fu_1121_p1 = r_V_8_2_1_fu_1116_p2[7:0];

assign tmp_7_fu_434_p2 = ($signed(10'd1023) + $signed(t_V_cast_fu_368_p1));

assign tmp_i_i_94_fu_1249_p2 = (overflow_fu_1235_p2 | isneg_reg_1506);

assign tmp_i_i_fu_1225_p2 = (isneg_reg_1506 ^ 1'd1);

assign tmp_s_fu_384_p2 = ((t_V_reg_322 < 9'd480) ? 1'b1 : 1'b0);

assign x_fu_800_p3 = ((sel_tmp8_fu_794_p2[0:0] === 1'b1) ? p_p2_i_i_cast1_fu_750_p1 : sel_tmp_cast_fu_778_p1);

assign y_1_fu_570_p3 = ((or_cond_i424_i_fu_466_p2[0:0] === 1'b1) ? tmp_39_cast_fu_440_p2 : p_p2_i425_i_p_assign_8_fu_562_p3);

always @ (posedge ap_clk) begin
    OP2_V_1_2_cast_reg_1368[11:4] <= 8'b00000000;
    OP2_V_2_1_cast_reg_1378[10:3] <= 8'b00000000;
end

endmodule //Filter2D
